//
// The MIT License (MIT)
//
// Copyright 2020 Karolpg
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), 
// to deal in the Software without restriction, including without limitation the rights to #use, copy, modify, merge, publish, distribute, sublicense, 
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR #COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//

#include "SlackFileTypes.h"
#include <array>

const char* slackFileTypeStr(SlackFileType type)
{
#define SlackFileType_To_Str(x) ret[static_cast<uint32_t>(SlackFileType::x)] = #x;

    static const std::array<const char*, static_cast<uint32_t>(SlackFileType::count_SlackFileType)> strs = [] {
        std::array<const char*, static_cast<uint32_t>(SlackFileType::count_SlackFileType)> ret;
        SlackFileType_To_Str(autoType   )
        SlackFileType_To_Str(text       )
        SlackFileType_To_Str(ai         )
        SlackFileType_To_Str(apk        )
        SlackFileType_To_Str(applescript)
        SlackFileType_To_Str(binary     )
        SlackFileType_To_Str(bmp        )
        SlackFileType_To_Str(boxnote    )
        SlackFileType_To_Str(c          )
        SlackFileType_To_Str(csharp     )
        SlackFileType_To_Str(cpp        )
        SlackFileType_To_Str(css        )
        SlackFileType_To_Str(csv        )
        SlackFileType_To_Str(clojure    )
        SlackFileType_To_Str(coffeescript)
        SlackFileType_To_Str(cfm        )
        SlackFileType_To_Str(d          )
        SlackFileType_To_Str(dart       )
        SlackFileType_To_Str(diff       )
        SlackFileType_To_Str(doc        )
        SlackFileType_To_Str(docx       )
        SlackFileType_To_Str(dockerfile )
        SlackFileType_To_Str(dotx       )
        SlackFileType_To_Str(email      )
        SlackFileType_To_Str(eps        )
        SlackFileType_To_Str(epub       )
        SlackFileType_To_Str(erlang     )
        SlackFileType_To_Str(fla        )
        SlackFileType_To_Str(flv        )
        SlackFileType_To_Str(fsharp     )
        SlackFileType_To_Str(fortran    )
        SlackFileType_To_Str(gdoc       )
        SlackFileType_To_Str(gdraw      )
        SlackFileType_To_Str(gif        )
        SlackFileType_To_Str(go         )
        SlackFileType_To_Str(gpres      )
        SlackFileType_To_Str(groovy     )
        SlackFileType_To_Str(gsheet     )
        SlackFileType_To_Str(gzip       )
        SlackFileType_To_Str(html       )
        SlackFileType_To_Str(handlebars )
        SlackFileType_To_Str(haskell    )
        SlackFileType_To_Str(haxe       )
        SlackFileType_To_Str(indd       )
        SlackFileType_To_Str(java       )
        SlackFileType_To_Str(javascript )
        SlackFileType_To_Str(jpg        )
        SlackFileType_To_Str(keynote    )
        SlackFileType_To_Str(kotlin     )
        SlackFileType_To_Str(latex      )
        SlackFileType_To_Str(lisp       )
        SlackFileType_To_Str(lua        )
        SlackFileType_To_Str(m4a        )
        SlackFileType_To_Str(markdown   )
        SlackFileType_To_Str(matlab     )
        SlackFileType_To_Str(mhtml      )
        SlackFileType_To_Str(mkv        )
        SlackFileType_To_Str(mov        )
        SlackFileType_To_Str(mp3        )
        SlackFileType_To_Str(mp4        )
        SlackFileType_To_Str(mpg        )
        SlackFileType_To_Str(mumps      )
        SlackFileType_To_Str(numbers    )
        SlackFileType_To_Str(nzb        )
        SlackFileType_To_Str(objc       )
        SlackFileType_To_Str(ocaml      )
        SlackFileType_To_Str(odg        )
        SlackFileType_To_Str(odi        )
        SlackFileType_To_Str(odp        )
        SlackFileType_To_Str(ods        )
        SlackFileType_To_Str(odt        )
        SlackFileType_To_Str(ogg        )
        SlackFileType_To_Str(ogv        )
        SlackFileType_To_Str(pages      )
        SlackFileType_To_Str(pascal     )
        SlackFileType_To_Str(pdf        )
        SlackFileType_To_Str(perl       )
        SlackFileType_To_Str(php        )
        SlackFileType_To_Str(pig        )
        SlackFileType_To_Str(png        )
        SlackFileType_To_Str(post       )
        SlackFileType_To_Str(powershell )
        SlackFileType_To_Str(ppt        )
        SlackFileType_To_Str(pptx       )
        SlackFileType_To_Str(psd        )
        SlackFileType_To_Str(puppet     )
        SlackFileType_To_Str(python     )
        SlackFileType_To_Str(qtz        )
        SlackFileType_To_Str(r          )
        SlackFileType_To_Str(rtf        )
        SlackFileType_To_Str(ruby       )
        SlackFileType_To_Str(rust       )
        SlackFileType_To_Str(sql        )
        SlackFileType_To_Str(sass       )
        SlackFileType_To_Str(scala      )
        SlackFileType_To_Str(scheme     )
        SlackFileType_To_Str(sketch     )
        SlackFileType_To_Str(shell      )
        SlackFileType_To_Str(smalltalk  )
        SlackFileType_To_Str(svg        )
        SlackFileType_To_Str(swf        )
        SlackFileType_To_Str(swift      )
        SlackFileType_To_Str(tar        )
        SlackFileType_To_Str(tiff       )
        SlackFileType_To_Str(tsv        )
        SlackFileType_To_Str(vb         )
        SlackFileType_To_Str(vbscript   )
        SlackFileType_To_Str(vcard      )
        SlackFileType_To_Str(velocity   )
        SlackFileType_To_Str(verilog    )
        SlackFileType_To_Str(wav        )
        SlackFileType_To_Str(webm       )
        SlackFileType_To_Str(wmv        )
        SlackFileType_To_Str(xls        )
        SlackFileType_To_Str(xlsx       )
        SlackFileType_To_Str(xlsb       )
        SlackFileType_To_Str(xlsm       )
        SlackFileType_To_Str(xltx       )
        SlackFileType_To_Str(xml        )
        SlackFileType_To_Str(yaml       )
        SlackFileType_To_Str(zip        )
        return ret;
    }();
#undef SlackFileType_To_Str
    return strs[static_cast<uint32_t>(type)];
}
